<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Test Form</title>
    <script type="text/javascript" src="js/script.js"></script>
  </head>
  <body>
    <form>
      <ul>
        <li>
          <select name="type">
            <option value="Note">Note</option>
            <option value="Image">Image</option>
          </select>
        </li>
        <li>
          <input type="text" name="content" />
        </li>
        <li>
          <input type="text" name="to" />
        </li>
        <li>
          <button type="button" name="button">click</button>
        </li>
      </ul>
    </form>
  </body>
</html>
